gpt-4o: gpt-4o-2024-08-06
gpt-4o-mini: gpt-4o-mini

# Pair 1
llavaov_7b: llava-hf/llava-onevision-qwen2-7b-ov-hf
qwen_7b: Qwen/Qwen2-7B-Instruct

# Pair 2
llava: llava-hf/llava-v1.6-34b-hf
yi: NousResearch/Nous-Hermes-2-Yi-34B

# Pair 3
intern2_40b: OpenGVLab/InternVL2-40B
yi2: NousResearch/Nous-Hermes-2-Yi-34B

# Pair 4
internvl: OpenGVLab/InternVL2_5-38B
qwen: Qwen/Qwen2.5-32B-Instruct

# Pair 5
internvl_1: OpenGVLab/InternVL2_5-38B
r1_qwen32b: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
