# Closed sources
gpt4o-mini:
  vlm: gpt-4o-mini
  llm: gpt-4o-mini

gpt4o:
  vlm: gpt-4o-2024-08-06
  llm: gpt-4o-2024-08-06

# Open sources
# Pair 1
llavaov_7b:
  vlm: llavaov_7b
  llm: qwen_7b
qwen_7b:
  vlm: llavaov_7b
  llm: qwen_7b

# Pair 2
llava:
  vlm: llava
  llm: yi
yi:
  vlm: llava
  llm: yi

# Pair 3
intern2_40b:
  vlm: intern2_40b
  llm: yi2
yi2:
  vlm: intern2_40b
  llm: yi2

# Pair 4
internvl:
  vlm: internvl
  llm: qwen
qwen:
  vlm: internvl
  llm: qwen

# Pair 5
internvl_1:
  vlm: internvl_1
  llm: qwen
  reasoning: r1_qwen32b

r1_qwen32b:
  vlm: internvl_1
  llm: qwen
  reasoning: r1_qwen32b
